<<<<<<< HEAD
title: Lediana Berasa
description: Hallo ini website pribadi saya 

url: https://ledianaberasa.github.io/
=======
url: "https://ledianaberasa.github.io"
>>>>>>> 161d19ed0c78e4d06eb492310b5688e0a8a7fba5

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag